"""Concise SFT method: shortest correct CoT reasoning.

Self-Training Concise Reasoning (aligned with the original paper):
1. Load CoT samples (pre-generated by sample.py)
2. For each question:
   a. Filter to correct samples
   b. Deduplicate by reasoning text (paper: exact string match)
   c. Hard cutoff: discard samples with token_count >= max_think_tokens
   d. Score remaining candidates with reward_func, select the single best
3. Construct SFTSample with reasoning + answer (one per question)

Supports augmented mode: merge multiple CoT sample files (e.g. zero-shot + few-shot).
"""

import json
import logging
import warnings
from pathlib import Path

from sft.data.base import SFTSample
from ragen.env.reward_funcs import init_reward_func
from sft.methods.base import BaseSFTMethod

logger = logging.getLogger(__name__)


class ConciseMethod(BaseSFTMethod):
    """Concise SFT: train on shortest correct CoT reasoning."""

    name = "concise"

    def build_samples(
        self, benchmark: str, raw_data: list[dict], **kwargs
    ) -> list[SFTSample]:
        """Build Concise SFT samples from pre-generated CoT samples.

        Requires kwargs['cot_samples_path'] pointing to the output of sample.py.
        Supports multiple paths (comma-separated) for augmented mode.

        For each question, selects the shortest correct reasoning trace
        by token count (aligned with the original paper).
        """
        cot_samples_path = kwargs.get("cot_samples_path")
        if not cot_samples_path:
            raise ValueError(
                "ConciseMethod requires --cot-samples-path. "
                "Run `python -m sft.methods.self_training_concise.sample` first."
            )

        # Support comma-separated paths for augmented mode
        paths = [p.strip() for p in cot_samples_path.split(",")]
        for p in paths:
            if not Path(p).exists():
                raise FileNotFoundError(f"CoT samples not found: {p}")

        # Load and merge CoT samples from all paths, indexed by source_id
        # For each question, merge samples from all files
        cot_by_id: dict[str, list] = {}
        for p in paths:
            with open(p) as f:
                for line in f:
                    record = json.loads(line)
                    sid = record["source_id"]
                    if sid not in cot_by_id:
                        cot_by_id[sid] = {
                            "source_id": sid,
                            "question": record["question"],
                            "gold_answer": record["gold_answer"],
                            "samples": [],
                        }
                    cot_by_id[sid]["samples"].extend(record["samples"])

        if len(paths) > 1:
            logger.info(f"Augmented mode: merged {len(paths)} CoT files")

        max_think_tokens = kwargs.get("max_think_tokens", None)

        # Reward function for scoring candidates (shared with RL pipeline).
        # Default: linear length reward, equivalent to "select shortest".
        reward_func_config = kwargs.get("reward_func", None)
        if reward_func_config is not None:
            reward_func = init_reward_func(reward_func_config)
        else:
            # Default to linear reward; max_length only affects relative
            # ranking so we use a large value as fallback.
            reward_func = init_reward_func({
                "type": "linear",
                "max_length": max_think_tokens or 2048,
            })

        samples = []
        skipped_no_cot = 0
        skipped_no_correct = 0
        skipped_dedup = 0

        for item in raw_data:
            source_id = item["source_id"]

            cot_record = cot_by_id.get(source_id)
            if cot_record is None:
                skipped_no_cot += 1
                continue

            # Step 1: Filter to samples with valid think content
            valid_samples = [
                s for s in cot_record["samples"]
                if s.get("think") and s["think"].strip()
            ]

            # Step 2: Deduplicate by reasoning text (paper: exact string match)
            seen_texts = set()
            deduped = []
            for s in valid_samples:
                text = s["think"].strip()
                if text not in seen_texts:
                    seen_texts.add(text)
                    deduped.append(s)
            skipped_dedup += len(valid_samples) - len(deduped)
            valid_samples = deduped

            # Step 3: Score with reward_func, keep only reward > 0.
            # reward_func handles both correctness (wrong -> 0) and length
            # (too long -> 0) in one step.
            scored = []
            for s in valid_samples:
                original_reward = 1.0 if s["is_correct"] else 0.0
                token_count = s.get("think_token_count", s.get("think_length", 0))
                score = reward_func(original_reward, token_count)
                if score > 0:
                    scored.append((s, score))

            if not scored:
                skipped_no_correct += 1
                continue

            # Step 4: Select the single best candidate per question
            # (paper: pick the shortest correct, equivalent to max reward)
            best, _ = max(scored, key=lambda x: x[1])

            samples.append(SFTSample(
                question=item["question"],
                answer=best["answer"],
                reasoning=best["think"],
                benchmark=benchmark,
                method="concise",
                source_id=source_id,
            ))

        if skipped_no_cot > 0:
            warnings.warn(f"Skipped {skipped_no_cot} questions: no CoT samples found")
        if skipped_no_correct > 0:
            warnings.warn(
                f"Skipped {skipped_no_correct} questions: no correct CoT sample"
            )

        logger.info(
            f"Concise SFT: {len(samples)} samples from {len(raw_data)} questions "
            f"(skipped: {skipped_no_cot} no CoT, {skipped_no_correct} no correct, "
            f"dedup removed: {skipped_dedup})"
        )
        return samples
